id = "grok-4-1-fast-reasoning"
name = "Grok 4.1 Fast Reasoning"
provider_model_id = "grok-4-1-fast-reasoning"
knowledge = "2025-07"
release_date = "2025-11-19"
last_updated = "2025-11-19"

[limits]
context = 2000000
output = 30000

[cost]
input = 0.2
output = 0.5
cache_read = 0.05

[modalities]
input = ["text", "image"]
output = ["text"]

[capabilities.reasoning]
enabled = true

[capabilities.tools]
enabled = true

[extra]
attachment = true
open_weights = false
temperature = true
