# Google Provider Definition
id = "google"
name = "Google"
base_url = "https://generativelanguage.googleapis.com/v1beta"
doc = "https://ai.google.dev/docs"

env = ["GOOGLE_API_KEY"]

exclude_models = [
  "gemini-1.0-pro-001",
  "gemini-1.0-pro-002",
  "gemini-1.0-pro-vision-001",
  "gemini-1.5-flash",
  "gemini-1.5-flash-001",
  "gemini-1.5-flash-002",
  "gemini-1.5-flash-8b",
  "gemini-1.5-pro",
  "gemini-1.5-pro-001",
  "gemini-1.5-pro-002",
  "gemini-live-2.5-flash-preview-native-audio",
  "gemini-live-2.5-flash",
  "gemini-2.5-flash-preview-04-17",
  "gemini-2.5-pro-preview-05-06",
  "gemini-2.5-pro-preview-06-05",
  "gemini-2.5-flash-lite-preview-06-17",
  "gemini-2.5-flash-lite-preview-09-2025",
  "gemini-2.5-flash-preview-09-2025",
  "gemini-flash-lite-latest",
  "gemini-2.5-flash-image-preview",
  "gemini-2.5-flash-preview-tts",
  "gemini-2.5-pro-preview-tts",
  "embedding-001",
  "embedding-gecko-001",
  "gemini-embedding-exp-03-07",
  "gemini-embedding-exp",
]
